---
version: "2"
linters:
  default: all
  exclusions:
    paths:
      - ".*_test.go"
      - "examples/"
  disable:
    - depguard
    # it should improve to support more known patterns
    - varnamelen
    - revive
    - ireturn
    - wrapcheck
    - cyclop
