---
version: 2
issues:
  exclude-files:
    - ".*_test.go"
linters:
  enable-all: true
  disable:
    - depguard
    # it should improve to support more known patterns
    - varnamelen
    - revive
    - ireturn
