---
issues:
  exclude-files:
    - ".*_test.go"
linters:
  enable-all: true
  disable:
    - depguard
    # it should improve to support more known patterns
    - varnamelen
    # deprecated linters
    - revive
    - ireturn
    - cyclop
    - wrapcheck
    - nolintlint
    - exportloopref
